### ISSUE TITLE
Adding eclipse .dotfiles to gitignore

### ISSUE THREAD

**Issue by MaSven** [LucasBullen/corrosion#29] opened 2018-02-09 21:24 UTC
When running 
``
mvn clean verify
``
for the first time after importing it in eclipse, you get the error 

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:1.0.0:build-qualifier (default-build-qualifier) on project org.eclipse.corrosion: Working tree is dirty.
[ERROR] git status org.eclipse.corrosion:
[ERROR] 
[ERROR] Changes not staged for commit:
[ERROR] 	modified:    org.eclipse.corrosion/.gitignore
[ERROR] 
[ERROR] Untracked files:
[ERROR] 	org.eclipse.corrosion/.settings/org.eclipse.m2e.core.prefs
[ERROR] 
[ERROR] You are trying to use tycho-buildtimestamp-jgit on a directory that has uncommitted changes (see details above).
[ERROR] Either commit all changes/add files to .gitignore, or enable fallback to default timestamp provider by configuring 
[ERROR] jgit.dirtyWorkingTree=warning for tycho-packaging-plugin
[ERROR] -> [Help 1]

because of the generated dotfiles for eclipse.
Adding those files to .gitignore would help for this. Also this files are generated when importing the project as maven project.

**Comment by LucasBullen** [comment] 2018-02-09 21:43
Tell me if e4fd24a fixes your problem.

**Comment by MaSven** [comment] 2018-02-09 21:54
not really iam still getting 

>[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:1.0.0:build-qualifier (default-build-qualifier) on project org.eclipse.corrosion: Working tree is dirty.
[ERROR] git status org.eclipse.corrosion:
[ERROR] 
[ERROR] Changes not staged for commit:
[ERROR] 	modified:    org.eclipse.corrosion/.gitignore
[ERROR] 	modified:    org.eclipse.corrosion/.classpath
[ERROR] 	modified:    org.eclipse.corrosion/.project

have a look at my pull request #30 for all dotfiles that must be ignored. Also the auto generated files of maven.

**Comment by LucasBullen** [comment] 2018-02-12 13:33
Classpaths and project files are quite often included in project repos as far as I've seen, what is the modifications that have happened in your .classpath and .project files?

**Comment by mickaelistria** [comment] 2018-02-12 14:17
the `.project`, `.classpath` and even `.settings/` are better being kept in the Git repo as per Eclipse IDE recommendations. Valuable changes on that files should be committed.
Those files are not expected to be modified without a reason. If they are, it's something that should be fixed in the tool that modifies those files without reason, not something that Eclipse Plugin project should workaround by removing the files.

**Comment by LucasBullen** [comment] 2018-02-13 15:27
@MaSven, I see you closed #30. Did you solve the issue? If there were some actions you were required to take to get it to work, could you post them here for future reference by others?

**Comment by MaSven** [comment] 2018-02-13 15:32
Ok i think the problem is, 
* made a new git clone to have a clean state
*  import the project as maven project from parent. 
* Start maven clean verify from within eclipse.
* Eclipse will now alter the .gitignore file, .classpath file ,the .project file and some files in the settings folder.
* mvn clean verify will fail because of the altered files

Here is what changed. 
[0001-Altered-files-from-import-as-maven-project.txt](https://github.com/LucasBullen/corrosion/files/1720460/0001-Altered-files-from-import-as-maven-project.txt)

**Comment by mickaelistria** [comment] 2018-02-13 15:40
@LucasBullen I think it's be good to accept those changes in dotfiles caused by m2e, once and for all. The only drawback is that m2e would become required, but the vast majority of Plugins Developers do have it installed and other ones would be prompted to install it, so it wouldn't be a big deal.

**Comment by MaSven** [comment] 2018-02-13 15:41
I closed it because i think the description isn't appropriate anymore for this issue.

**Comment by MaSven** [comment] 2018-02-13 15:45
Should i start a new pull request then? Or will somebody of you too make a new commit?

**Comment by LucasBullen** [comment] 2018-02-13 15:52
I've reverted my last commit, feel free to make the new pull request.

**Closed** 2018-02-15 15:07 UTC
